# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8007b49230405661a0c92a3f758c0344407347ca8235b23365de823b93166994603382377bfc580d512914ac5344fccd0e3ac92ff4601401c1f3f1422e44613e

test:
  secret_key_base: d62aafc38a73992d406283f1e391ea6a775fff1fcbcaef2e0039f506c17134916ef5a12e1c94659bf5c2c24b9ba90dfdab0ebd23e68f48afe29233d63b7166e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
